### ISSUE TITLE
Broken link in http://uchicago.mobi/sessions/session2/

### ISSUE THREAD

**Issue by cassamanojc** [uchicago-mobi/mpcs51030-2017-summer-forum#10]
In http://uchicago.mobi/sessions/session2/
Under Session Materials, the “Slides” link works , but the Class Playground Repository, which points to https://github.com/uchicago-mobi/mpcs51030-2017-summer-playground, doesn’t seem to find the resources (github returns a 404 page)

**Comment by tabinks** [comment]
Good catch.  

There are no playgrounds yet for class.  It's picking up the link from a template.  I'll fix it.
