### ISSUE TITLE
Graduating Student Projects

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#100]
If any of the graduating students would like the opportunity to show off their projects tonight, *please let me know*.  I will leave a couple of minutes after the break for them.

These students do not have to put together any slides or make a formal presentation, just the chance to show off using the simulator or on a device if they choose.

Thanks.

**Comment by Gloria-Xiaolu-Zhang** [comment]
Hi Andrew,
I would like to show (no off here) my final project tonight :) Hope it's not too late to sign up!
Also, will you hold office hour before or after class today? Need some help in a feature. Thanks!
Gloria

**Comment by tabinks** [comment]
As long as you don't show a really sad video about a mountain climber, that is fine. I'm on my way in and will be sitting on 306 until class starts.
