### ISSUE TITLE
What is a Splash Screen?

### ISSUE THREAD

**Issue by acham1** [uchicago-mobi/mpcs51030-2017-summer-forum#104]
I don't think I understand what a splash screen is :-/

> Applications should show a splash screen with (at least) the developer’s name and the name of the application. This should appear when your application launches. This is not the same as the Launch Screen that is provided in Storyboard.

**Comment by tabinks** [comment]
Basically a view that shows when the app comes to the foreground.  There are many ways of implementing it (see #88 for some ones you have done).
