### ISSUE TITLE
How to fetch existing view controllers in another view controller

### ISSUE THREAD

**Issue by BingWangEd** [uchicago-mobi/mpcs51030-2017-summer-forum#106]
Hi, I have several view controllers defined each by a separate view controller class. Now I'd like to add these view controllers to a page view controller. 

All of the online tutorials tell me to create a page as follows:

let page1: UIViewController! = storyboard?.instantiateViewController(withIdentifier: "page1")

Then add it to the pageviewdata. But the problem is I don't need to instantiate these view controllers again. They are defined already by their own classes. Is there a method similar to:

let page1: UIViewController! = storyboard?.ViewController(findbyIdentifier: "page1")

So I can find existing viewcontrollers and add them to the page view data?

I hope I have made myself clear.

Thanks,
Bing

**Comment by tabinks** [comment]
If they are already instantiated then it will not create a new instance of it. You can use this and either way it will ensure that one is available.

**Comment by BingWangEd** [comment]
Hi, Prof,

It does not seem to work in my case though. The pageview works perfectly fine, until I add a classViewController to one of the pages. The viewcontroller is empty. Once I remove its class name. It works again. This is part of my code:

class CsiPageViewController: UIPageViewController, UIPageViewControllerDataSource, UIPageViewControllerDelegate {
    
    var pages = [UIViewController]()
    var pageControl = UIPageControl()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        self.delegate = self
        self.dataSource = self
        
        let page1: UIViewController! = storyboard?.instantiateViewController(withIdentifier: "page1")
    
        let page2: UIViewController! = storyboard?.instantiateViewController(withIdentifier: "page2")
        
        pages.append(page1)
        pages.append(page2)
        
        setViewControllers([page1], direction: UIPageViewControllerNavigationDirection.forward, animated: false, completion: nil)
        
        configurePageControl()
    }

...

**Comment by tabinks** [comment]
Can you commit your latest version.  I'll take a look at it.

**Comment by BingWangEd** [comment]
Hi, Prof, that'd be great. I just push the codes.

Right now, I set the initial page to be the PageViewController. It's not working. But if you delete custom class: CsiPageOneViewController in the ViewController with "Give your project a title." It will work.

Thanks,
Bing

**Comment by tabinks** [comment]
I looked at it and I think that the problem is that `CsiPageOneViewController` should not be a subclass of `UIPageViewController`.  A `UIPageViewController` should manage view controllers not additional `UIPageViewController`s.  In your project the only `UIPageViewController` subclass should be `CsiPageViewController`.  All the pages you want it to load should be plain old `UIViewController` subclasses.

**Comment by BingWangEd** [comment]
Thanks prof! It works now!!!!
