### ISSUE TITLE
Best way to update a uilabel from a different view controller

### ISSUE THREAD

**Issue by BingWangEd** [uchicago-mobi/mpcs51030-2017-summer-forum#108]
Hi, in my final project, I need to input text in one view controller, and then the data needs to be saved and updated in a final output view controller. I am trying to implement it this way.
In the view controller that asks users to input a title, I set a function:
@IBOutlet weak var titleText: UITextField!
@IBAction func editEnded(_ sender: Any) {
        let outputVC = storyboard?.instantiateViewController(withIdentifier: "page5") as! OutputViewController
        outputVC.projectTitle.text=titleText.text!
    }

In my outputVC, there's a projectTitle label. However, this is not working. The data gets lost once I left the current view controller. I have three questions here:
1. Is this way not the right one to approach this issue? Or is it that I didn't implement it correctly?
2. I have done some research online, and it seems that most people recommend using "NotificationCenter"
3. I don't think "segue" will work to pass the data to page 5 in this case, because the next view is not the final output view. Is that correct?

Thanks,
Bing

**Comment by tabinks** [comment]
NotificationCenter would be one way to make it work.  The other would be to save the value to `UserDefaults` and then you would be able to read it anywhere in the app (in your case, the other view controller).

**Comment by BingWangEd** [comment]
Like the one we did before. Thanks!
