### ISSUE TITLE
App Rating Alert

### ISSUE THREAD

**Issue by acham1** [uchicago-mobi/mpcs51030-2017-summer-forum#109]
> **Alerts**
> - Applications should utilize an UIAlertView somewhere within the application
>  - If it is not part of the normal user interface of your application, Have the alert view
prompt users “Rate this App” in the app store on the 5th launch.

Does this mean we need to have a "Rate this App" alert, only if there isn't a UIAlertView elsewhere in the application?

**Comment by hbennett766** [comment]
Yep, that's correct.

**Comment by acham1** [comment]
Thanks!
