### ISSUE TITLE
Link not loading

### ISSUE THREAD

**Issue by SuperSocrates** [uchicago-mobi/mpcs51030-2017-summer-forum#11]
Hi,

Having an issue with the Ray Wunderlich tutorial. The link to it on Session 2 Notes page is not loading anything for me. On Safari I get a blocked plugin message even though I have allow plugins selected in preferences. On Chrome nothing loads at all. The weirdest part is I was able to get it to load a few days ago, but not today. I guess I'll download Firefox and see if that works.

Also, figured I'd mention it here since I haven't heard back yet, I am unable to add anyone as collaborators to my first assignment. The Settings link is not showing up on the GitHub page. I promise I'm not normally this much of an internet noob!

**Comment by SuperSocrates** [comment]
Ah, figured out how to get it load in Chrome. Carry on! But, if you can help me with the GitHub issue I would much appreciate it.

**Comment by hbennett766** [comment]
When set as private, the instructors and TA's can still see/download/grade your repos, no need to add us as collaborators. If there's some other reason that you need to add collaborators that I'm missing, lmk!

**Comment by tabinks** [comment]
I just checked links on safari and they do work.  Everything is hosted on Guthub, may just be a server issue on their end.  Slides are s bug download so it takes a while to load.

**Comment by SuperSocrates** [comment]
Thank you both for the responses!
