### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by cassamanojc** [uchicago-mobi/mpcs51030-2017-summer-forum#12]
It looks like assignment 3 (description in the course webpage, and repo 3) has not been posted yet. Any chance it will be posted sometime today?

**Comment by tabinks** [comment]
I was going to post it at 5:30 after Assignment 2 was due.  Since you asked, I will post it earlier...around noon when I get in front of a computer.

**Comment by cassamanojc** [comment]
Thank you! It looks like I might have misunderstood in class -- I thought I had a recollection that assignments were going to be posted on Tuesdays (yesterday, which was a holiday), and would be due on Wednesdays (ie. after one week and one day).
Apologies!
