### ISSUE TITLE
Office Hours on Thursday from 11:00-12:30 in Young 306

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#14]
I will have office hours on Thursday (July 6) from 11:00-12:30 in Young 306.   Please stop by to chat about assignments, final projects, or anything else iOS related.

**Comment by ghost** [comment]
Hi, Is it possible to put office hour after 6pm or at weekend? some student are working full-time. So they could also have the chance to chat with you.

**Comment by tabinks** [comment]
My normal office hours will be before/after class on Tuesday just for this reason.  I am holding them tomorrow to make up for the Holiday this Tuesday.

**Comment by ghost** [comment]
Got it, Thanks
