### ISSUE TITLE
Make-up class date

### ISSUE THREAD

**Issue by BingWangEd** [uchicago-mobi/mpcs51030-2017-summer-forum#16]
Hi, 

In the form regarding our availability for making up classes, there was no date specified.

If no one has strong preference, I would really appreciate it if the make-up class **is not** put during the week of 17th, as I will be out of town due to work the week of 18th - 23rd, and it can be a bit hard for me to catch up missing two classes. 

Of course, it depends on the professor, TAs, and everyone else's schedule. I understand it if that's the best week for everyone else.

Thanks,
Bing

**Comment by tabinks** [comment]
I just wanted to see what days would work before suggesting dates.  I will be sending out another form with exact dates so that I can get preferences.

**Comment by BingWangEd** [comment]
Thanks!
