### ISSUE TITLE
Assignment 3

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#17]
Link: http://uchicago.mobi/sessions/session3/
Repo: https://classroom.github.com/assignment-invitations/45415d07129fcdd851d39ebbd8bbe318

**Comment by majonathany** [comment]
Hi,

I just wanted to verify for HW #3, for the iOS tutorial, we basically want to do from: "Build a Basic UI" (already completed) --> "Persist Data" (inclusive), correct?

Also, we should do from "Adding the About Screen" --> "The End... or the Beginning" (inclusive), correct?

Thanks!

**Comment by hbennett766** [comment]
Yep! That's correct.
