### ISSUE TITLE
Virtual Office Hours Saturday 10am-12pm

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/mpcs51030-2017-summer-forum#2]
Hey everyone! I'm Hannah, and I'm one of the TA's for this quarter. I'll be holding office hours on the tables outside Young on Saturday morning. Why outside? Partially because it's supposed to be a beautiful day, partially because my ID doesn't get me into Young anymore, but mostly because I'm babysitting a dog this weekend, and I don't trust her in my apartment alone, so she's coming with me.

Please let me know if you're going to come hang out! I'll more than gladly meet in person, but if no one plans to show up, I'll just hold virtual office hours and field spur-of-the-moment questions.

**Comment by tabinks** [comment]
There is a 2 dog treat minimum per question :)

**Comment by hbennett766** [comment]
Office hours are officially virtual. If you have an questions this morning, post in the forum or shoot me an email at hbennett766@gmail.com. We can set up video chat time if need be.
