### ISSUE TITLE
Xcode crashes when I try to edit Text View

### ISSUE THREAD

**Issue by SuperSocrates** [uchicago-mobi/mpcs51030-2017-summer-forum#21]
Anyone else having an issue with Xcode crashing? I'm working on the Bull's Eye app, and when I try to add the About screen text to the Text View (page99), Xcode crashes. It does so whether I copy/paste or type straight into the box. Googling had some hits but nothing that seemed directly relevant. Help?

**Comment by SuperSocrates** [comment]
I think it has something to do with skipping lines, because if I type gibberish without pressing option+return, nothing happens. But as soon as I press option+enter (or paste the text from the pdf which has skipped lines in it), the crash happens. And yes, I'm sure I'm using a Text View and not a Text Field, already recreated it just to be sure.

**Comment by SuperSocrates** [comment]
Okay, I found a workaround for now by pasting the text into the text box on the Attributes Inspector on the right instead. In case anyone else has this issue.

**Comment by hbennett766** [comment]
I can check out your project. Is your repo up to date?

**Comment by SuperSocrates** [comment]
It is now.

**Comment by tjlynch15** [comment]
I had the same issue, and used the same workaround.

**Comment by hbennett766** [comment]
Your code/storyboard looks good to me, and even if it wasn't, it shouldn't cause all of Xcode to crash, just your app. This looks like an Xcode bug, nothing you can do.
