### ISSUE TITLE
set image size issue

### ISSUE THREAD

**Issue by xuefeng11** [uchicago-mobi/mpcs51030-2017-summer-forum#22]
Hi, 
I am following the instruction, when I try to set the size of image to 105, it auto set back to 104.5
please advise.
thanks
![image](https://user-images.githubusercontent.com/16236593/27997209-dcb836a6-64b8-11e7-9348-254a21c812b2.png)

**Comment by hbennett766** [comment]
It looks like you have a layout constraint error (or errors). That could be causing the sizing issues. Click that red arrow in the top right corner to see what Xcode is complaining about.

**Comment by xuefeng11** [comment]
It's a horizontal vague issue, I fixed. But still not able to set it to 105.
I checked the official example , it's also 104.5 , not able to set to 105, either.

**Comment by hbennett766** [comment]
If the layout constraints are resolved (which they are), and Xcode wants it to be 104.5, my best advice is to just let it have its way. Sometimes Xcode does weird things like that. I've seen this happen before in my own work for no apparent reason.

**Comment by tabinks** [comment]
This is good (but probably frustrating advice).  Constraints are set by solving an equation that satisfies all the dimensions of the objects and your constraints, so sometimes you don't get exactly what you want. 

FYI: There are ways to weight your constraints using the `priority` property of constraints.  This allows you to let the auto-layout system which constraints are the most important...in the case something might be ambiguous.  Using this is (in my opinion) a bit of a black box.  The values aren't scaled in any meaningful way and it basically requires a bunch of trial and error to get the value you want....but it does work...just not clear why it works or what exactly is happening.

**Comment by xuefeng11** [comment]
Got it, Thanks!
