### ISSUE TITLE
Unable to change constraint background dimensions in (Bull's Eye)

### ISSUE THREAD

**Issue by cassamanojc** [uchicago-mobi/mpcs51030-2017-summer-forum#23]
Any idea where I might have gone wrong?
Upon setting setting the dimensions for the background image (in the Bull's Eye game) in page 126, first, I don't to see the option "Update Frames" (could this be related to the Xcode version, I am on Version 8.3.3 (8E3004b).

But the real problem:
After I check "Horizontally in Container" and "Vertically in Container" and click "Add 2 Constraints", the background image resizes (to much smaller dimensions -- at least it does go to the center), and Xcode doesn't seem to like the fact that I try to resize it (ie. it retrieves warnings). But whether I resize (whichever dimensions) or not the simulator reflects the smaller size.
<img width="1405" alt="screen shot 2017-07-09 at 4 04 54 pm" src="https://user-images.githubusercontent.com/29682310/27997583-cc018c7e-64c0-11e7-8ae7-141282a81941.png">

**Comment by hbennett766** [comment]
For "updating frames", checkout this [stackoverflow post](https://stackoverflow.com/questions/40320043/xcode-8-1-how-to-update-frames-for-all-views-in-a-storyboard).

For your constraints issues, you've got some options. For both, start by dragging/expanding the image to fit the full container. Then:

1. Add constraints to make the width and height of the image equal to the width and height of the container. When you do the control drag from the image to the container, they'll be the constraints titled "equal widths" and "equal heights".

or

2. Set the leading, trailing, top, and bottom constraints of the image. This will pin the sides of the image to the sides of the container.

Let me know if either of these work!

**Comment by cassamanojc** [comment]
Thank you! These work.
