### ISSUE TITLE
Creating scroll view

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#28]
I think in last night's lecture it was stated that for assignment 4 the scroll view should be created programmatically vs. via the storyboard. Just wondering if I heard this correctly, and if so why this is the case, when the object library for the storyboard does include a scroll view object?

**Comment by prazgaitis** [comment]
Consider it a good opportunity to practice creating things programmatically! 

There is a big debate in the iOS developer community between using storyboards and doing it in code. A lot of devs prefer to do everything in code, and not use storyboards at all.

Here's an interesting take on it: https://medium.com/@kenzai/why-i-stopped-using-storyboards-and-interface-builder-a9142e060f71

**Comment by acham1** [comment]
So, just to double-check, does this override the assignment instructions saying:
> Add a UIScrollView using storyboard.

The instructions say to create it by storyboard, and then set properties programmatically?

**Comment by tabinks** [comment]
Yes.  You should add it to your Storyboard using Interface Builder, but you will find that you will need to set some properties on programmatically.
