### ISSUE TITLE
Slides for Tonight

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#3]
https://github.com/uchicago-mobi/uchicago-mobi.github.io/raw/master/sessions/session2/mpcs51030-2017-summer-lecture2.pdf

**Comment by tabinks** [comment]
Links fixed on site.

**Comment by meyermt** [comment]
Thanks for posting! Is there a new repo we should be using for hw2?

**Comment by tabinks** [comment]
@meyermt see #5
