### ISSUE TITLE
TA office hours?

### ISSUE THREAD

**Issue by SuperSocrates** [uchicago-mobi/mpcs51030-2017-summer-forum#30]
Hi, 

I must have missed the details on this but do the TAs have office hours and if so, what time? Thanks!

**Comment by hbennett766** [comment]
Yep, mine are either Saturday or Sunday morning, 10am-12pm ish. I'll post the exact day and time each week here in the forum. The variety is to fit as many schedules as possible.

**Comment by prazgaitis** [comment]
Mine will be this sunday morning at 10am in Young. I will make a separate post to announce.

**Comment by SuperSocrates** [comment]
Great, thank you both!
