### ISSUE TITLE
Paul Office Hours this week, and in general

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/mpcs51030-2017-summer-forum#31]
I will be holding office hours this **Sunday** at 10am in Young. 

If you are interested in attending, please comment on this issue. If you are interested and you live downtown, please note that as well - I can hold them at the Gleacher center as well if there is more demand for that. 

If you would rather have office hours during the week, let me know! I am happy to accommodate that if it works better than Sunday. 

Last, if there are no replies to this issue, I will hold virtual office hours. Instead we can do a Google Hangout and I'll be happy to answer questions via Hangouts.

**Comment by BingWangEd** [comment]
Hi, Paul,

Apologies for the late response. I wonder if you could put the 10 am office hour downtown? I'm planning to attend. I'm also happy to do a google hangout.

Thanks,
Bing

**Comment by prazgaitis** [comment]
Hi Bing, lets do it via Hangouts this time, and next time I can do the office hours downtown. I will post the hangouts link here closer to 10am.

**Comment by BingWangEd** [comment]
Thanks!!

**Comment by prazgaitis** [comment]
Here's the link:

https://hangouts.google.com/call/esdypbp5lva7zjeemvjpzazugyu

**Comment by prazgaitis** [comment]
From Q&A:

One way to check if the UIImage has scrolled is to use a switch statement in `scrollViewDidEndDecelerating`.

```swift
func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        let x = scrollView.bounds.minX
        switch x {
        case 0:
            animalNameLabel.text = animalsArray2[0].name
        case 414:
            animalNameLabel.text = animalsArray2[1].name
        case 828:
            animalNameLabel.text = animalsArray2[2].name
        default:
            animalNameLabel.text = animalsArray2[0].name  
        }
    }
```
You can do it this way for this project, but if you had a dynamic array, you would probably want to dynamically fetch the array contents as well, instead of writing n number of switch statements.

**Comment by tjlynch15** [comment]
Hi Paul:

I used a similar method, and it works, but I used minX multiples of 375, which is the visible width of the scrollView. Just wondering why you are using multiples of 414?

Thanks

**Comment by prazgaitis** [comment]
I was optimizing the app for a different screen size (i believe it was the iPhone 7). You can optimize for any device you'd like for this project, but a best practice would be to get the screen size dynamically like this:

```swift
let screenSize = UIScreen.main.bounds
let screenWidth = screenSize.width
```

**Comment by tjlynch15** [comment]
Thanks Paul

**Comment by SuperSocrates** [comment]
Hi Paul, for this week are you doing office hours at the same time Sunday? Any chance you can do them tomorrow? I need some help on both the scroll view assignment and this week's.

**Comment by prazgaitis** [comment]
@SuperSocrates i posted about my office hours (will be Sunday from 5-7pm), feel free to send over your questions and the repo link and I can take a look sooner, too!

prazgaitis [at] uchicago [dot] edu
