### ISSUE TITLE
index of Animal object

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#36]
I am trying to find a built in function that returns the index of an Animal object. For example, in an array, animals, of Animal objects:

for animal in animals {
    let animalInd = animals.index(of: animal)    
}

However, when I try this, I get an error: "Cannot invoke 'index' with an argument list type (of: animal).

This should be pretty simple. Any suggestions?

**Comment by tabinks** [comment]
I just ran this in a Playground and it worked fine:
```swift
let animals = ["dog","cat","rabbit"]

for animal in animals {
  let animalInd = animals.index(of: animal)
  print(animalInd) 
}
```
It prints:
```swift
Optional(0)
Optional(1)
Optional(2)
```

**Comment by tjlynch15** [comment]
OK, thanks! I'll try it again.

**Comment by tjlynch15** [comment]
Just a thought, does it matter if its a String vs. Animal object?

**Comment by tabinks** [comment]
Yup, that's probably the problem.  You will probably need to write a custom subscript for your class.  See the docs:  https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Subscripts.html 

Alternatively, you could just write your own `findIndexOfObject()` function that iterates through the collection.

**Comment by tjlynch15** [comment]
OK, thanks.
