### ISSUE TITLE
Links to Ray Wenderlich tutorials

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#37]
It seems that most of the links for the tutorials on the session 4 page all point to the same tutorial (tutorial 1). I am particularly interested in tutorial 5 that has information on how to play sounds, but haven't found a way to get there.

**Comment by hbennett766** [comment]
Here's the link to "making it beautiful":
https://www.raywenderlich.com/27191/learn-to-code-ios-apps-4-making-it-beautiful

This one has the links to parts 1, 2, and 3 at the top.
