### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by SuperSocrates** [uchicago-mobi/mpcs51030-2017-summer-forum#38]
In the instructions, it says "Create a custom Swift data class named Animal."

Does this mean the template should be "Swift File?" Or "Cocoa Touch Class?" I am assuming Swift file, and my understanding is that the only difference is the default template ("Cocoa Touch" importing UIKit, and the other only Foundation). But then I saw that one of the properties is a UIImage, so should it be Cocoa touch after all?

Edit: The screenshot in the instructions also seems to be using Objective-C instead of Swift so that was a little confusing.

**Comment by SuperSocrates** [comment]
I'm guessing it's a Swift File class and I just need to add "Import UIKit" at the top, but just wanted to be sure.

**Comment by hbennett766** [comment]
Good question! There's no difference between a "Swift File" and a "Cocoa Touch Class" besides the default code that it starts you out with in the template. As you noticed, Swift File gives you Foundation, and Cocoa Touch Class gives you UIKit. So the important question here is...

**"What's the difference between importing Foundation and importing UIKit?"**

Importing [Foundation](https://developer.apple.com/documentation/foundation) gives you access to Apple's basic "data types, collections, and operating-system services". So things like Array, String, Dictionary, etc.

Importing [UIKit](https://developer.apple.com/documentation/uikit) gives you access to iOS-specific standard APIs, such as UITableView, UIViewController, and Touch event handling. UIKit includes Foundation in the background, so importing UIKit means you should not also import Foundation.

Whichever you choose to start with, Swift File or Cocoa Touch Class, is fine. The important part is knowing which imports are right for each file. View controllers will need UIKit, while objects may only need Foundation.

**Comment by SuperSocrates** [comment]
Thanks, that was very helpful!
