### ISSUE TITLE
make text fade in and out

### ISSUE THREAD

**Issue by BingWangEd** [uchicago-mobi/mpcs51030-2017-summer-forum#40]
Hi, 

I'm not so sure about how to make the label text fade in and out. In scrollViewDidEndDecelerating, you check the scrollview.contentSetoff and base on that, you change the content of labels. But do you add animation in scrollViewDidEndDecelerating as well?

Thanks,
Bing

**Comment by tabinks** [comment]
You should look at adjusting the `.alpha` property of the `UILabel`.  Using the `.contentOffset` you will know how what percent of each image is on the screen.  Use that percentage to adjust the `.alpha` property.

**Comment by BingWangEd** [comment]
it works now. Thanks!
