### ISSUE TITLE
Final project deadline for graduating students

### ISSUE THREAD

**Issue by Gloria-Xiaolu-Zhang** [uchicago-mobi/mpcs51030-2017-summer-forum#45]
Hi Andrew and TAs,

Hope you are having a good night! I may have missed it. When is the deadline of final project for graduating students? I believe our grades need to be up by Aug.19, which is the Sat. of week 9.

Thanks!
Gloria

**Comment by tabinks** [comment]
Final projects for graduating students will be due **Wednesday, August 16th at 11:59PM**.
