### ISSUE TITLE
Looking for partner

### ISSUE THREAD

**Issue by liuzix** [uchicago-mobi/mpcs51030-2017-summer-forum#46]
Hi, my name is Zixiondg Liu. My email is lzx@uchicago.edu. Email me if you want to team up.

**Comment by majonathany** [comment]
Hi, have you found a partner? I am looking for one. Thanks!

**Comment by liuzix** [comment]
@majonathany  I am still looking. How about we meet and chat?

**Comment by majonathany** [comment]
Sounds good! I can meet tomorrow (10-2) or Monday anytime from 10 - 4:30. What works for you?

**Comment by liuzix** [comment]
I can do monday at 2:00. Why don't you send me an email?
