### ISSUE TITLE
Fetching issues

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#49]
I am trying to implement the Fetching Issues code from the session 5 playground in my homework project. When I run it in the playground, it runs fine. When I run the exact same code in my homework project, I get an Expected Declaration error. Can't figure out what the problem is. I have uploaded my code to GitHub. Any guidance would be greatly appreciated!

**Comment by tjlynch15** [comment]
I get the expected declaration error when I call the getIssues function.

**Comment by tabinks** [comment]
`getIssues()` is calling the the function, my guess is that the way you have it in the view controller that Xcode thinks you are trying to declare it as a function.
<img width="922" alt="screenshot 2017-07-21 08 54 45" src="https://user-images.githubusercontent.com/93689/28466682-d06ef39c-6df2-11e7-8535-21c08af46d44.png">
