### ISSUE TITLE
Repos for Assignment 2

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#5]
https://classroom.github.com/assignment-invitations/ebabe3eb96e3e4043d787a1ffbda9915

**Comment by majonathany** [comment]
Hi, 

I was wondering - I noticed this on HW #1, that when you are in the storyboard editor, and you do the control + drag for a UI element into the source file to create an outlet, and then say hypothetically, you don't want it anymore, you have do two things. It seems like only deleting it in the ViewController source is not sufficient - you also have to delete its reference by right-clicking the UI element in the storyboard editor and deleting the relationship. Is this normal/true? Is there any way to do both actions at once (deleting from source and delete the UI element's relationship)?

Thanks!

**Comment by hbennett766** [comment]
This is in fact normal/true. It's a two step process, there's no shortcut to delete both at the same time.
