### ISSUE TITLE
Final Project

### ISSUE THREAD

**Issue by quackquackquackquack** [uchicago-mobi/mpcs51030-2017-summer-forum#50]
Hello! 
Wondering if we can share a few examples / description of previous years' projects that can serve as a benchmark re. complexity and expectations for our project. 

Any other benchmarks (e.g., min 3 views, use of API, etc.) too might be helpful! 
Thanks!

**Comment by tabinks** [comment]
I will show off a couple of them during lecture.

**Comment by quackquackquackquack** [comment]
Lovely! Thanks so much!!
