### ISSUE TITLE
Case Study Schedule

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#57]
* July 25
  - Alan Cham, Michael Meyer (Yo)
  - Xuefeng Li
* August 1
  - Sundeep Kumar, Gloria Zhang (Dating Apps)
  - BingWangEd, TBD (TBD)
  - Jonathan Ma
* August 8
  - Terry Lynch, Tom Regan (TBD) 
  - Joao Cassamano (JC)
  - Samantha Rey
* August 11
   - Sam Joen, Jonathan Ly (Wunderlist)
   - Nathan Somayaji
* August 15
  - George Gulotta, Nate (Tinder)
  - Yuxiao Sun

**Comment by tabinks** [comment]
# I will be filling in the rest of the spaces tonight at 9:00PM.  If you haven't filled out the form in #47 than you will be assigned a partner and time.

**Comment by BingWangEd** [comment]
Hi, all, 

I have been out of town for an intense training and missed this past week's class. Was not aware of this till now. Would really appreciate if you don't assign me to present next week.

Will try to find a partner asap.

Best,
Bing
