### ISSUE TITLE
Office Hours 4-5p Young

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/mpcs51030-2017-summer-forum#58]
Note the time change! Compressed them due to low response.

**Comment by BingWangEd** [comment]
Hi, any chance that you or any other TA could meet tomorrow? I've been out of town. I can do google hangout or come to your area to meet. Any time tomorrow is good for me. Thanks!

**Comment by hbennett766** [comment]
Yeah, I can meet with you. How's 8pm? I can either meet virtually or at the starbucks on the corner of Harrison and Dearborn. Doesn't matter which, lmk which you want to do!

**Comment by BingWangEd** [comment]
Hi, I was on a flight. Just saw this. Yes, Monday (today) 8 pm works for me! Harrison and Dearborn is a perfect location. I live very close. Really appreciate it!
