### ISSUE TITLE
Finding Swift Man Pages?

### ISSUE THREAD

**Issue by acham1** [uchicago-mobi/mpcs51030-2017-summer-forum#6]
Are there any swift man pages? 
For instance, in this week's assignment, a function "lroundf" is used to convert the slider's float value to an integer. I wanted to look up the man pages for this function, not so much because the function itself is complicated, but rather because I wished to get a sense of what other functions are there rather than just have them appear out of the blue (I didn't see any special math library imports, so I assume functions like "lroundf" are part of some built-in Swift standard library).

I searched the Swift Standard Library page: https://developer.apple.com/documentation/swift
But I only got these results for macOS/Objective-C, nothing for iOS/Swift
![screen shot 2017-06-29 at 7 11 34 am](https://user-images.githubusercontent.com/13604807/27686864-3bcbf6ea-5c9a-11e7-8e02-3cfd04a165e7.png)

And even when I opened those results, there was basically no information in those pages
![screen shot 2017-06-29 at 7 12 56 am](https://user-images.githubusercontent.com/13604807/27686928-74b6c3f4-5c9a-11e7-8eed-10e7f5737b41.png)

So where is the right place to look for things like this? I'm hoping to find something like the Swift-equivalent for the Java API specs, or the GNU C library reference man? 
Thanks!

**Comment by acham1** [comment]
It happens again when they use arc4random_uniform() to generate a random target. I mean, if the tutorial didn't happen to involve that function, I'm not sure how I would ever have known that function was available. And this time, searching on the [Swift Standard Library](https://developer.apple.com/documentation/swift) page doesn't yield any results for this function at all afaik, so I'd have to just infer what this function does without any official spec? Am I just looking in the wrong place?

**Comment by tabinks** [comment]
There isn't a real satisfying answer to this.  These are functions that have been in Cocoa frameworks for decades.  As with any language there is some stuff that is really well documented and some stuff that is just discovered when you need it. For example, if you had googled how do I  generate a random number in swift this would have most certainly come up as the top answer.

Another good resource for learning more about functions is to look at the header files in the frameworks.

**Comment by acham1** [comment]
I guess it's just a different approach for me to get accustomed to then. I do trust the google results, and the aggregate experience/expertise of other Swift users posting in forums, but it just feels a little "hand-wavey" for now. I can live with it though; thanks :-)

**Comment by tabinks** [comment]
With 21,000+ APIs, it does take a slightly different approach.
