### ISSUE TITLE
Final projects

### ISSUE THREAD

**Issue by ggulotta** [uchicago-mobi/mpcs51030-2017-summer-forum#69]
Do we need to get our ideas approved beforehand? For that matter, is are there specific requirements? Is there a rubric we need to follow?

**Comment by tabinks** [comment]
After you submit your ideas, I will send out an email  to let you know if it looks good or if I have any suggestions.

**Comment by tabinks** [comment]
We will discuss some specific requirements for the project, but overall, it is very open ended.

**Comment by ggulotta** [comment]
Cool. When do we need to submit those?

**Comment by tabinks** [comment]
@ggulotta See #75   You can submit them to me now via email.
