### ISSUE TITLE
loading Subview

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#74]
I have created a game over subview that I am trying to call when a player wins. I can call this function in ViewDidLoad as a test, and it works. But when I try to call from the function that checks for a winner, it is called, but the view doesn't display. Can't figure out what I am missing.

Thanks

**Comment by tabinks** [comment]
If you are moving it on/off the screen.  Make sure that you are starting/stopping in the correct position...or at least where you think it is.  If you call it in viewDidLoad and it moves down, then it will be offscreen the second time you call.  Just one thought.

**Comment by tjlynch15** [comment]
At this point, I'm not moving it. Just loading it.

**Comment by prazgaitis** [comment]
Here's a tutorial that shows how to do this with a xib file in storyboard:

http://zappdesigntemplates.com/create-your-own-overlay-view-in-swift/

Here's a quick repo I made that does the same thing without xibs, just programmatically:

https://github.com/prazgaitis/swift-subview-demo

**Comment by tjlynch15** [comment]
Thanks Paul

I don't think their is anything wrong with my game ended view function, as I am able to call it directly from ViewDidLoad, and it presents fine. And when I call my about view using a button, it works fine. I am basically using the same code to complete the respective views. The problem, I believe, is that I am trying to call the game ended view from an if statement, and not from a button action. In the if statement, the function for the view is called (as verified by inclusion of print statements), but the view is not visible.
