### ISSUE TITLE
Gesture recognizer selector from another class

### ISSUE THREAD

**Issue by sinkingrowboats** [uchicago-mobi/mpcs51030-2017-summer-forum#78]
So, I've been able to get the gesture recognizer handler to work when the function is in the same class
`let pan = UIPanGestureRecognizer(target: self, action: #selector(XOImageView.dragXO(_:)))`

however, when I try 

`let pan = UIPanGestureRecognizer(target: self, action: #selector(ViewController.dragXO(_:)))`

I get an error that the selector is unrecognized. I've looked around for solutions online and haven't found anything. Any advice?

**Comment by hbennett766** [comment]
Is your repo up to date? I can pull down your project and check it out tonight.

**Comment by tjlynch15** [comment]
Yes. Thanks. I'm also going to see if I can talk to Andrew before class tonight.

**Comment by hbennett766** [comment]
Ok cool, keep me posted

**Comment by sinkingrowboats** [comment]
Hello, repo is up to date
The code blocks of interest are lines 29-32 ish of XOImageView.swift and lines 55-60 of ViewController.swift

**Comment by sinkingrowboats** [comment]
also the dragXO functions at the bottom of XOImageView and ViewController respectively

**Comment by hbennett766** [comment]
Leaving a note here for myself that you and Paul figured this one out during the class break.
