### ISSUE TITLE
Assignment 7 Question - Casting json

### ISSUE THREAD

**Issue by tjlynch15** [uchicago-mobi/mpcs51030-2017-summer-forum#83]
I am able to retrieve json data, but am having trouble figuring out how to cast as an array of dictionaries. I have tried several different ways. I understand the instructions: "You should used the RelatedTopics key to retrieve an array of dictionaries of the results." But the syntax is giving me fits. I have tried to modify the code from project 4 as follows:

guard let issues = json as? [[String: [String: AnyObject]]] else {               
                  fatalError("We couldn't cast the JSON to an array of dictionaries")
                }

I keep getting the fatal error. Any suggestions?

**Comment by tabinks** [comment]
It looks like you are trying to cast an array of dictionaries of dictionaries.
