### ISSUE TITLE
Final Project Requirements

### ISSUE THREAD

**Issue by tabinks** [uchicago-mobi/mpcs51030-2017-summer-forum#88]
We will also discuss this in class tonight.
[mpcs51030-2016-summer-FinalProjectRequirements.pdf](https://github.com/uchicago-mobi/mpcs51030-2017-summer-forum/files/1209282/mpcs51030-2016-summer-FinalProjectRequirements.pdf)

**Comment by sinkingrowboats** [comment]
I'm having trouble figuring out how to make a splash screen that is separate of the launch screen. Most resources on how to make a splash screen actually give how to make a launch screen. Any resources/advice?

**Comment by tabinks** [comment]
Just treat it as a view that appears and reappears at the appropriate time, similar to the tic tac toe custom alert view, but just is the size of the screen.  

Or, just use a view controller and present it modally.
