### ISSUE TITLE
Early office hours on Sunday (8/13) - 9am to 11am Gleacher center cafeteria

### ISSUE THREAD

**Issue by prazgaitis** [uchicago-mobi/mpcs51030-2017-summer-forum#89]
Nothing better than Swiftin' on a Sunday morning!

I'll bring the donuts, BYOC (bring your own coffee - just because I can't carry that on my bike!)

Let me know if you plan to attend!

![donuts](https://media.giphy.com/media/NKFTsaVXwtB1S/giphy.gif)

**Comment by quackquackquackquack** [comment]
+1!

**Comment by SuperSocrates** [comment]
I'm planning to be there.
