### ISSUE TITLE
Office Hours Rescheduled

### ISSUE THREAD

**Issue by hbennett766** [uchicago-mobi/mpcs51030-2017-summer-forum#95]
I'm going to be out of town for an extended weekend, and therefore won't be able to hold office hours this weekend. However, I will make them up next week/weekend and still do two sessions before final projects are due. Hopefully this will work out to your benefit, as final projects will be further along by then.

**Comment by SuperSocrates** [comment]
Can they be midweek if possible? That way some time between them and the next set on the weekend. Have a nice trip!

**Comment by hbennett766** [comment]
Yeah, I can do midweek! I was planning on Thursday evening at Gleacher. I'll post the exact time early next week.
